apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ghes-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ghes-vm
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: root-disk
            bootOrder: 1
          - disk:
              bus: virtio
            name: data-disk
            bootOrder: 2
          interfaces:
          - name: default
            bridge: {}
            ports:
            - port: 8443
              protocol: TCP
            - port: 8080
              protocol: TCP
            - port: 122
              protocol: TCP
            - port: 1194
              protocol: UDP
            - port: 123
              protocol: UDP
            - port: 161
              protocol: UDP
            - port: 443
              protocol: TCP
            - port: 80
              protocol: TCP
            - port: 22
              protocol: TCP
            - port: 9418
              protocol: TCP
            - port: 25
              protocol: TCP
        resources:
          requests:
            memory: "12Gi"
            cpu: "2"
          limits:
            memory: "12Gi"
            cpu: "2"
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: ghes-root-dv
        name: root-disk
      - dataVolume:
          name: ghes-data-dv
        name: data-disk        

