apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ghes-vm
spec:
  dataVolumeTemplates:
  - metadata:
      name: ghes-dv-5
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 250Gi
      source:
        http:
          url: https://github-enterprise.s3.amazonaws.com/kvm/releases/github-enterprise-2.17.1.qcow2
  - metadata:
      name: ghes-dv-6
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
            path: /dev/vdb
      source:
        blank: {}
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ghes-vm
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: root-disk
            bootOrder: 1
          - disk:
              bus: virtio
            name: data-disk
            dedicatedIOThread: true
          interfaces:
          - name: default
            bridge: {}
            ports:
            - port: 8443
              protocol: TCP
            - port: 8080
              protocol: TCP
            - port: 122
              protocol: TCP
            - port: 1194
              protocol: UDP
            - port: 123
              protocol: UDP
            - port: 161
              protocol: UDP
            - port: 443
              protocol: TCP
            - port: 80
              protocol: TCP
            - port: 22
              protocol: TCP
            - port: 9418
              protocol: TCP
            - port: 25
              protocol: TCP
        resources:
          requests:
            memory: 16Mi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: ghes-dv-5
        name: root-disk
      - dataVolume:
          name: ghes-dv-6
        name: data-disk
      # - name: root-disk
      #   persistentVolumeClaim:
      #     claimName: ghes-dv-4
      #    - disk:
      #        bus: virtio
      #      name: data-disk
      #      bootOrder: 2
