# GitHub Enterprise Server Data Volume resources
#
# Learn more: https://github.com/kubevirt/containerized-data-importer/blob/master/doc/datavolumes.md

# Data volume for the GHES VM
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ghes-root-dv
spec:
  source:
    http:
      url: https://github-enterprise.s3.amazonaws.com/kvm/releases/github-enterprise-2.17.1.qcow2
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 250Gi
---

# Data volume for user data
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ghes-data-dv
spec:
  source:
    blank: {}
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
